import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] })
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 }, permissions: ['camera'] })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
await page.goto('http://localhost:5173/#/', { waitUntil: 'networkidle' })
await page.evaluate(() => window.scrollTo(0, 560))
await page.screenshot({ path: 'e2e/screenshots/hub.png' })
const cards = await page.locator('[data-testid^="game-card-"]').count()
await page.goto('http://localhost:5173/#/play/beep-meow-whoosh', { waitUntil: 'networkidle' })
await page.screenshot({ path: 'e2e/screenshots/intro.png' })
await page.getByRole('button', { name: '☝️ Point a finger' }).click()
const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('wiggleplay.settings.v1')).global.interaction)
await page.getByRole('button', { name: '🧍 Whole body' }).click()
await page.goto('http://localhost:5173/#/about', { waitUntil: 'networkidle' })
await page.screenshot({ path: 'e2e/screenshots/about.png' })
const aboutText = await page.locator('main').innerText()
console.log({ cards, storedAfterFingerClick: stored, aboutMentionsAuthor: aboutText.includes('Atul Tiwari'), errors })
await browser.close()
