import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] })
const context = await browser.newContext({ viewport: { width: 1280, height: 720 }, permissions: ['camera'] })
const page = await context.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
await page.goto('http://localhost:5173/#/play/wave-pop', { waitUntil: 'networkidle' })
await page.getByRole('button', { name: '▶ Play' }).click()
await page.waitForFunction(() => !document.querySelector('.overlay'), null, { timeout: 60000 })
await page.waitForTimeout(1500)
const gear = page.getByRole('button', { name: 'Hold for settings' })
const box = await gear.boundingBox()
await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
await page.mouse.down()
await page.waitForTimeout(400)
const early = await page.locator('.settings').count()
await page.waitForTimeout(900)
await page.mouse.up()
const open = await page.locator('.settings').count()
await page.getByLabel(/^Bubbles on screen/).fill('15')
await page.getByLabel(/^Sound effects/).fill('3')
await page.screenshot({ path: 'e2e/screenshots/settings-open.png' })
const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('wiggleplay.settings.v1')))
await page.getByRole('button', { name: 'Close settings' }).click()
await page.waitForTimeout(2500)
const bubbles = await page.evaluate(() => document.querySelector('.hud')?.textContent)
console.log({ early, open, maxBubbles: stored.wavePop.maxBubbles, effectsVolume: stored.global.effectsVolume, hud: bubbles, errors })
await browser.close()
